package br.com.bruno.pdv.util;

public enum Message {

    USUARIO_NAO_ENCONTRADO,
    ERRO_AO_DELETAR_USUARIO,
    USUARIO_DELETADO_COM_SUCESSO,
    STATUS_ATUALIZADO_COM_SUCESSO,
    ERRO_AO_ATUALIZAR_STATUS,
    PRODUTO_NAO_ENCONTRADO,
    PRODUTO_DELETADO_COM_SUCESSO,
    ERRO_AO_DELETAR_PRODUTO,
    VENDA_NAO_ENCONTRADA,
    VENDA_DELETADA_COM_SUCESSO,
    VENDA_REALIZADA_COM_SUCESSO_ID_,
    ERRO_AO_DELETAR_VENDA,
    SALE_NOT_FOUND_WITH_ID_,
    SEM_PRODUTO_NO_ESTOQUE_COM_ID_,
    ESTOQUE_PRODUTO_MENOR_QUE_A_QUANTIDADE_DA_VENDA_COM_ID_,
    ITEM_SEM_QUANTIDADE_INFORMADA_COM_ID_,
    SEM_PRODUTO_COM_ID_,
    SEM_USUARIO_COM_ID_,
    USUARIO_ATUALIZADO_COM_SUCESSO;

}
